updated /usr/local/bin scripts

diff --git a/configs/releng/airootfs/usr/local/bin/whenup b/configs/releng/airootfs/usr/local/bin/whenup
--- a/configs/releng/airootfs/usr/local/bin/whenup
+++ b/configs/releng/airootfs/usr/local/bin/whenup
@@ -1,4 +1,7 @@
 #!/bin/bash
+# a simple bash script to connect to a server when it is up
+# written by Jeremy Wakeman
+# SPDX-License-Identifier: GPL-3.0-or-later
 
 bell=0
 down=0
@@ -10,72 +13,82 @@ telnet=0
 onlytry=0
 options=0
 
-# if there's an issue with the command, print usage
-if [ "$*" == "" ] ; then
-	echo "Usage: whenup [-blortw] [-p <port to check>] <host to check> [command to execute]"
-	exit 1
-else
+# if help is requested, show usage and options
+if [[ "$*"" == " ]] || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]] ; then
+	exec_name=`basename $0`
+	echo "Usage: $exec_name [OPTION] <server>"
+	echo "connect to a server if it is up"
+	echo ""
+	echo "  -b,         bell when connecting"
+	echo "  -h, --help  display this help and exit"
+	echo "  -p [port]   check alternate port"
+	echo "  -w          wait 30 seconds between ping and connect"
+	echo "  -t          use telnet instead of ssh"
+	echo ""
+	echo "Examples:"
+	echo "  $exec_name -brw 192.168.0.1   use bell and wait, ssh root@192.168.0.1"
+	exit 0
+fi
 
-	# if options are passed, parse them
-	if [[  $1 =~ - ]] ; then
-		if [[ $1 =~ b ]] ; then
-			bell=1
-		fi
-		if [[ $1 =~ d ]] ; then
-			down=1
-		fi
-		if [[ $1 =~ l ]] ; then
-			loop=1
-		fi
-		if [[ $1 =~ o ]] ; then
-			onlytry=1
-		fi
-		if [[ $1 =~ w ]] ; then
-			wait=1
-		fi
-		if [[ $1 =~ r ]] ; then
-			root=1
-		fi
-		if [[ $1 =~ t ]] ; then
-			telnet=1
-		fi
-		if [[ $1 =~ p ]] ; then
-			port=$2
-			shift
-		fi
+# if options are passed, parse them
+if [[  $1 =~ - ]] ; then
+	if [[ $1 =~ b ]] ; then
+		bell=1
+	fi
+	if [[ $1 =~ d ]] ; then
+		down=1
+	fi
+	if [[ $1 =~ l ]] ; then
+		loop=1
+	fi
+	if [[ $1 =~ o ]] ; then
+		onlytry=1
+	fi
+	if [[ $1 =~ w ]] ; then
+		wait=1
+	fi
+	if [[ $1 =~ r ]] ; then
+		root=1
+	fi
+	if [[ $1 =~ t ]] ; then
+		telnet=1
+	fi
+	if [[ $1 =~ p ]] ; then
+		port=$2
 		shift
 	fi
-
-	# parse address or hostname to check
-	host=$1
 	shift
+fi
 
-	# if no command given, assume ssh the address or hostname
-	if [ "$*" == "" ] ; then
-		if [ "$root" == "1" ] ; then
-			if [ "$telnet" == "1" ] ; then
-				echo "Error: -r option and -t option should not be used together"
-				exit 1
-			fi
-			run="ssh root@$host"
-			port=22
-		elif [ "$telnet" == "1" ] ; then
-			run="telnet $host"
-			port=23
-		else
-			run="ssh $host"
-			port=22
+# parse address or hostname to check
+host=$1
+shift
+
+# if no command given, assume ssh the address or hostname
+if [ "$*" == "" ] ; then
+	if [ "$root" == "1" ] ; then
+		if [ "$telnet" == "1" ] ; then
+			echo "Error: -r option and -t option should not be used together"
+			exit 1
 		fi
+		run="ssh root@$host"
+		port=22
+	elif [ "$telnet" == "1" ] ; then
+		run="telnet $host"
+		port=23
 	else
-		if [ "$root" == "1" ] ; then
-			echo "Error: -r option should not be used with an explicit command"
-			exit 1
-		elif [ "$telnet" == "1" ] ; then
-			echo "Error: -t option should not be used with an explicit command"
-			exit 1
-		else
-			run=$*
-		fi
+		run="ssh $host"
+		port=22
+	fi
+else
+	if [ "$root" == "1" ] ; then
+		echo "Error: -r option should not be used with an explicit command"
+		exit 1
+	elif [ "$telnet" == "1" ] ; then
+		echo "Error: -t option should not be used with an explicit command"
+		exit 1
+	else
+		run=$*
 	fi
 fi
 
@@ -98,7 +111,7 @@ if [ "$wait" == "1" ] ; then
 fi
 # if we should bell, bell
 if [ "$bell" == "1" ] ; then
-	~/.bin/bell
+	bell
 fi
 
 runonce=1
@@ -128,7 +141,7 @@ while [[ $loop -eq 1 ]] || [[ $runonce -eq 1 ]] ; do
 	fi
 	# if we should bell, bell
 	if [ "$bell" == "1" ] ; then
-		~/.bin/bell
+		bell
 	fi
 	$run
 	if [[ $loop -eq 1 ]] ; then
